=== evandor/my-first-static-web-app/src/templates/patient-report/1.0/patient-report-schema.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "http://example.com/example.json",
  "type": "object",
  "default": {},
  "title": "Root Schema",
  "required": [
    "templateName",
    "patient",
    "od",
    "os"
  ],
  "properties": {
    "templateName": {
      "type": "string",
      "default": "",
      "title": "The templateName Schema",
      "examples": [
        "PatientReportTemplate"
      ]
    },
    "patient": {
      "type": "object",
      "default": {},
      "title": "The patient Schema",
      "required": [
        "firstName",
        "lastName",
        "decimalField",
        "integerField",
        "age",
        "comments"
      ],
      "properties": {
        "firstName": {
          "type": "string",
          "default": "",
          "title": "The firstName Schema",
          "examples": [
            "Heinz"
          ]
        },
        "lastName": {
          "type": "string",
          "default": "",
          "title": "The lastName Schema",
          "examples": [
            "Huber"
          ]
        },
        "decimalField": {
          "type": "number",
          "default": 0.0,
          "title": "The decimalField Schema",
          "examples": [
            25.5
          ]
        },
        "integerField": {
          "type": "integer",
          "default": 0,
          "title": "The integerField Schema",
          "examples": [
            10
          ]
        },
        "age": {
          "type": "integer",
          "default": 0,
          "title": "The age Schema",
          "examples": [
            76
          ]
        },
        "comments": {
          "type": "array",
          "default": [],
          "title": "The comments Schema",
          "items": {
            "type": "object",
            "title": "A Schema",
            "required": [
              "comment",
              "doctorEmail"
            ],
            "properties": {
              "comment": {
                "type": "string",
                "title": "The comment Schema",
                "examples": [
                  "Butchered the left eye.",
                  "Patient can see now for miles with right eye."
                ]
              },
              "doctorEmail": {
                "type": "string",
                "title": "The doctorEmail Schema",
                "examples": [
                  "dr.mabuse@gmail.com",
                  "dr.house@gmail.com"
                ]
              }
            },
            "examples": [
              {
                "comment": "Butchered the left eye.",
                "doctorEmail": "dr.mabuse@gmail.com"
              },
              {
                "comment": "Patient can see now for miles with right eye.",
                "doctorEmail": "dr.house@gmail.com"
              }
            ]
          },
          "examples": [
            [
              {
                "comment": "Butchered the left eye.",
                "doctorEmail": "dr.mabuse@gmail.com"
              },
              {
                "comment": "Patient can see now for miles with right eye.",
                "doctorEmail": "dr.house@gmail.com"
              }
            ]
          ]
        }
      },
      "examples": [
        {
          "firstName": "Heinz",
          "lastName": "Huber",
          "decimalField": 25.5,
          "integerField": 10,
          "age": 76,
          "comments": [
            {
              "comment": "Butchered the left eye.",
              "doctorEmail": "dr.mabuse@gmail.com"
            },
            {
              "comment": "Patient can see now for miles with right eye.",
              "doctorEmail": "dr.house@gmail.com"
            }
          ]
        }
      ]
    },
    "od": {
      "type": "object",
      "default": {},
      "title": "The od Schema",
      "required": [
        "laterality",
        "surgeon"
      ],
      "properties": {
        "laterality": {
          "type": "string",
          "default": "",
          "title": "The laterality Schema",
          "examples": [
            "OD"
          ]
        },
        "surgeon": {
          "type": "string",
          "default": "",
          "title": "The surgeon Schema",
          "examples": [
            "Dr. House"
          ]
        }
      },
      "examples": [
        {
          "laterality": "OD",
          "surgeon": "Dr. House"
        }
      ]
    },
    "os": {
      "type": "object",
      "default": {},
      "title": "The os Schema",
      "required": [
        "laterality",
        "surgeon"
      ],
      "properties": {
        "laterality": {
          "type": "string",
          "default": "",
          "title": "The laterality Schema",
          "examples": [
            "OS"
          ]
        },
        "surgeon": {
          "type": "string",
          "default": "",
          "title": "The surgeon Schema",
          "examples": [
            "Dr. Mabuse"
          ]
        }
      },
      "examples": [
        {
          "laterality": "OS",
          "surgeon": "Dr. Mabuse"
        }
      ]
    }
  },
  "examples": [
    {
      "templateName": "PatientReportTemplate",
      "patient": {
        "firstName": "Heinz",
        "lastName": "Huber",
        "decimalField": 25.5,
        "integerField": 10,
        "age": 76,
        "comments": [
          {
            "comment": "Butchered the left eye.",
            "doctorEmail": "dr.mabuse@gmail.com"
          },
          {
            "comment": "Patient can see now for miles with right eye.",
            "doctorEmail": "dr.house@gmail.com"
          }
        ]
      },
      "od": {
        "laterality": "OD",
        "surgeon": "Dr. House"
      },
      "os": {
        "laterality": "OS",
        "surgeon": "Dr. Mabuse"
      }
    }
  ]
}

=== evandor/my-first-static-web-app/src/templates/patient-report/1.0/patient-report-model.json
{
  "templateName": "PatientReportTemplate",
  "patient": {
    "firstName": "Heinz",
    "lastName": "Huber",
    "decimalField": 25.5,
    "integerField": 10,
    "age": 76,
    "comments": [
      {
        "comment": "Butchered the left eye.",
        "doctorEmail": "dr.mabuse@gmail.com"
      },
      {
        "comment": "Patient can see now for miles with right eye.",
        "doctorEmail": "dr.house@gmail.com"
      }
    ]
  },
  "od": {
    "laterality": "OD",
    "surgeon": "Dr. House"
  },
  "os": {
    "laterality": "OS",
    "surgeon": "Dr. Mabuse"
  }
}
