=== evandor/my-first-static-web-app/src/templates/order-sheet/1.0/partials/calculated-iol/calculated-iol-schema.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "https://zeiss.com/med/cataract/schemas/order-sheet/1/0/calculated-iol",
  "title": "Root Schema",
  "description": "The root schema is the schema that comprises the entire JSON document.",
  "type": "object",
  "default": {},
  "required": [
    "iolRefractivePowerSphericalEquivalent",
    "iolRefractivePowerSphere",
    "iolRefractivePowerCylinder",
    "iolRefractivePowerAxis",
    "residualRefractionSphericalEquivalent",
    "residualRefractionSphere",
    "residualRefractionCylinder",
    "residualRefractionAxis",
    "residualRefractionAxisFlipping"
  ],
  "additionalProperties": true,
  "properties": {
    "iolRefractivePowerSphericalEquivalent": {
      "title": "The iolRefractivePowerSphericalEquivalent Schema",
      "description": "An explanation about the purpose of this instance.",
      "type": "number",
      "default": 0.0,
      "examples": [
        24.5
      ]
    },
    "iolRefractivePowerSphere": {
      "title": "The iolRefractivePowerSphere Schema",
      "description": "An explanation about the purpose of this instance.",
      "type": "number",
      "default": 0.0,
      "examples": [
        23.375
      ]
    },
    "iolRefractivePowerCylinder": {
      "title": "The iolRefractivePowerCylinder Schema",
      "description": "An explanation about the purpose of this instance.",
      "type": "number",
      "default": 0.0,
      "examples": [
        2.25
      ]
    },
    "iolRefractivePowerAxis": {
      "title": "The iolRefractivePowerAxis Schema",
      "description": "An explanation about the purpose of this instance.",
      "type": "number",
      "default": 0.0,
      "examples": [
        100.0
      ]
    },
    "residualRefractionSphericalEquivalent": {
      "title": "The residualRefractionSphericalEquivalent Schema",
      "description": "An explanation about the purpose of this instance.",
      "type": "number",
      "default": 0.0,
      "examples": [
        0.06
      ]
    },
    "residualRefractionSphere": {
      "title": "The residualRefractionSphere Schema",
      "description": "An explanation about the purpose of this instance.",
      "type": "number",
      "default": 0.0,
      "examples": [
        0.32
      ]
    },
    "residualRefractionCylinder": {
      "title": "The residualRefractionCylinder Schema",
      "description": "An explanation about the purpose of this instance.",
      "type": "number",
      "default": 0.0,
      "examples": [
        -0.52
      ]
    },
    "residualRefractionAxis": {
      "title": "The residualRefractionAxis Schema",
      "description": "An explanation about the purpose of this instance.",
      "type": "number",
      "default": 0.0,
      "examples": [
        0.0
      ]
    },
    "residualRefractionAxisFlipping": {
      "title": "The residualRefractionAxisFlipping Schema",
      "description": "An explanation about the purpose of this instance.",
      "type": "boolean",
      "default": false,
      "examples": [
        true
      ]
    }
  },
  "examples": [
    {
      "iolRefractivePowerSphericalEquivalent": 24.5,
      "iolRefractivePowerSphere": 23.375,
      "iolRefractivePowerCylinder": 2.25,
      "iolRefractivePowerAxis": 100.0,
      "residualRefractionSphericalEquivalent": 0.06,
      "residualRefractionSphere": 0.32,
      "residualRefractionCylinder": -0.52,
      "residualRefractionAxis": 0.0,
      "residualRefractionAxisFlipping": true
    }
  ]
}

=== evandor/my-first-static-web-app/src/templates/order-sheet/1.1/partials/calculated-iol/calculated-iol-model.json
{
  "iolRefractivePowerSphericalEquivalent": 24.5,
  "iolRefractivePowerSphere": 23.375,
  "iolRefractivePowerCylinder": 2.25,
  "iolRefractivePowerAxis": 100.0,
  "residualRefractionSphericalEquivalent": 0.06,
  "residualRefractionSphere": 0.32,
  "residualRefractionCylinder": -0.52,
  "residualRefractionAxis": 0.0,
  "residualRefractionAxisFlipping": true
}
